version: '3.7'
services: 
  mysql:
    image: mysql
    ports:
      - 9003:3306
      - 33060:33060
    container_name: mysql
    hostname: mysql
    volumes:
      - {REPLACE THIS WITH YOUR LOCAL PATH}:/var/lib/mysql
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.7
      - MYSQL_MAJOR=8.0
      - MYSQL_VERSION=8.0.16-2debian9
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - {REPLACE THIS WITH YOUR LOCAL PATH}:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitUser
      - RABBITMQ_DEFAULT_PASS=rabbitPass
      - PATH=/opt/rabbitmq/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - OPENSSL_VERSION=1.1.1b
      - OPENSSL_SOURCE_SHA256=5c557b023230413dfb0756f3137a13e6d726838ccd1430888ad15bfb2b43ea4b
      - OPENSSL_PGP_KEY_ID=0x8657ABB260F056B1E5190839D9C4D26D0E604491
      - OTP_VERSION=21.3.8.2
      - OTP_SOURCE_SHA256=a45bc309b40c507934606723187cb6cdbae547a677d7c52168849864d1ea1c68
      - RABBITMQ_DATA_DIR=/var/lib/rabbitmq/mnesia
      - RABBITMQ_VERSION=3.7.15-management
      - RABBITMQ_PGP_KEY_ID=0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
      - RABBITMQ_HOME=/opt/rabbitmq
      - RABBITMQ_LOGS=-
      - RABBITMQ_SASL_LOGS=-
      - HOME=/var/lib/rabbitmq
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
  serviceregistration:
    image: "serviceregistration"
    container_name: "serviceregistration"
    build: "../ServiceRegistration"
    ports: 
      - 9000:9000
    hostname: "serviceregistration"
    volumes:
      - "/tmp"
  cloudgateway:
    image: cloudgateway
    container_name: cloudgateway
    build: "../CloudGateway"
    ports:
      - 9001:9001
    hostname: cloudgateway
    volumes:
      - "/tmp"
    depends_on:
      - "serviceregistration"
  repository:
    image: repository
    container_name: repository
    hostname: repository
    build: "../Repository"
    ports:
      - 9011:9011
    volumes:
      - "/tmp"
    depends_on:
      - "serviceregistration"
      - "mysql"
  testservice:
    build: ../TestService
    image: testservice
    ports:
      - 9010:9010
    container_name: testservice
    hostname: testservice
    volumes:
      - "/tmp"
    depends_on:
      - "serviceregistration"
      - "rabbitmq"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=smartheating_db
      - DATABASE_PORT=3306
    
networks:
  default:
    external:
      name: "smartheating"
  