version: '3.7'
services: 
  serviceregistration:
    image: "serviceregistration"
    container_name: "serviceregistration"
    build: "../ServiceRegistration"
    ports: 
      - 9000:9000
    hostname: "serviceregistration"
    volumes:
      - "/tmp"