version: '3.3'
services: 
  preprocessing:
    image: preprocessing
    container_name: preprocessing
    build: "/smart_heating/Preprocessing"
    ports:
      - 9013:9013
    hostname: preprocessing
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - PRIVATE_IP=${PRIVATE_IP}
      - SERVICE_REGISTRATION_PRIVATE_IP=${SERVICE_REGISTRATION_PRIVATE_IP}
      - RABBITMQ_PRIVATE_IP=${RABBITMQ_PRIVATE_IP}
    volumes:
      - "/tmp"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"