version: '3.3'
services: 
  cloudgateway:
    image: cloudgateway
    container_name: cloudgateway
    build: "/smart_heating/CloudGateway"
    ports:
      - 9001:9001
    hostname: cloudgateway
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - PRIVATE_IP=${PRIVATE_IP}
    volumes:
      - "/tmp"