version: '3.3'
services: 
  mysql:
    image: mysql
    ports:
      - 3306:3306
      - 33060:33060
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.7
      - MYSQL_MAJOR=8.0
      - MYSQL_VERSION=8.0.16-2debian9
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - PUBLIC_IP=${PUBLIC_IP}
      - PRIVATE_IP=${PRIVATE_IP}
